name: CI Build

on: [push, pull_request]

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  JDK_Matrix:
    strategy:
      matrix:
        java: [ 11, 15 ]
        os: [ ubuntu-latest ]
        include:
        - os: windows-latest
          java: 8
        - os: ubuntu-latest
          java: 8
          codecov: true
          canonical: ${{ (github.repository == 'rotty3000/osgi-test-example-mvn') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/release')) && (github.event_name != 'pull_request') }}
          mavenopts: -Pjacoco
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.mavenopts }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      id: build
      run: |
        ./.github/scripts/build.sh ${{ matrix.mavenopts }}
